---
langs: [fr_FR, en_US]
baseurl: "/jeedom-myaudi" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- vendor
plugins:
- jekyll-paginate
- jekyll-seo-tag
title: "Rocket.chat"
description: "Ceci est la documentation du plugin Rocket.chat de la solution domotique Jeedom."
author: "Mips2648"
image: https://www.jeedom.com/site/logo.png
forum: https://community.jeedom.com/tags/plugin-myaudi
tagPlugin: plugin-myaudi
